regex_filters = {
    "text": [
        "Hi Dustie",
        "Hi Dustie and Team",
        "Hello BPM support",
        "SUPPORT ",
        "Good day",
        "Hello Team",
        "Dear Support",
        "Many thanks",
        "Good Day Lorraine I hope you are keeping well",
        "Hi Lorraine",
        "Dear Blueworkslive support",
        "RE: IBM523 Account See attached image",
        "To who may concern",
        "Lorraine",
        "Dear team",
        "Matt, I apologize for the inconvenience",
        "Dear Team",
        "Hey Len. Favour as usual",
        "Thilie",
        "Good Morning",
        "BARCLAYS CLASSIFICATION: Restricted - External Hi team",
        "Hi support",
        "Good Afternoon",
        "Kenya Brown Principal Consultant",
        "Blueworks Support",
        "Hello Blueworks Live account administrators",
        "Hello Blueworks Live Support",
        "Len, Thanks, as always, for your help",
        "Hi Jason/BWL support",
        "Hello support team",
        "Hi Blueworks Live",
        "Thanks Bob",
        "Hello good morning",
        "Dear Sender",
        "Michelle, Blueworks Support Team",
        "Support",
        "Hi Blueworks",
        "Hi Chris I am Thilini from Blueworks Live support",
        "Thank you Thilini",
        "Please call me at 202.267.5998",
        "Hello Wayne",
        "Dear all",
        "Blueworks Live",
        "Dustie ",
        "Christine ",
        "Blue Works",
        "blue work",
        "Greg ",
        "BWL ",
        "team ",
        "dear support",
        "dear bwl support team",
        "dear all",
        "hello blueworks support team",
        "good evening all",
        "i am thilini from support",
        "I hope this e-mail finds you well"
    ],
    "regex": [
        "Thanks(.*)",
        "Best Regards(.*)",
        "Copyright(.*)",
        "Kind Regards(.*)",
        "Many thanks(.*)",
        "Cheers(.*)",
        "Dustie Shelton(.*)",
        "Dpne @SUPPORT(.*)",
        "Best(.*)",
        "Thank you(.*)",
        "--(.*)",
        "__(.*)",
        "Sincerely(.*)",
        "Warm regards(.*)",
        "Regards(.*)",
        "Alok Ranjan(.*)",
        "The original request(.*)",
        "Respectfully(.*)",
        "Sent from my iPhone(.*)",
        "grantr@etihad.ae From: Grant Roberts Sent:(.*)",
        "Kindly advise(.*)",
        "Dawn Dawn Dodds(.*)",
        "Nadine.(.*)",
        "product_brand:Blueworks Live,(.*)",
        "Cleng Jissamy C.(.*)",
        "Natalia Perez(.*)",
        "Delroy Rookwood(.*)",
        "done Account:Rimova Expiration Current:(.*)",
        "Waiting your kind reply(.*)",
        "Stefan Erlandsson(.*)",
        "Thanks You(.*)",
        "Account:FenwickStoresGroup Expiration Current: 06/30/2018(.*)",
        "Please join us for this FREE(.*)",
        ">(.*)",
        "Delivery has failed to these recipients or groups:(.*)",
        "Account:ConnectforHealthConnectColorado Expiration Current:(.*)",
        "Tim Graham(.*)",
        "Easy peasy(.*)",
        "This e-mail message is(.*)",
        "???(.*)",
        "Sent from(.*)",
        "procurement operations process(.*)",
        "this e-mail and any attachments are intended only for the named recipient(.*)",
        "associate director(.*)",
        "Director, , : john.cannon@militarycars.com (.*)",
        "This e-mail is confidential, may be legally privileged. (.*)",
        "\| Card Scheme Development \|(.*)",
        "\| Client Technical Enablement- Process Transformation(.*)",
        "\| \| Sr. Managing Consultant \|(.*)",
        "\| Solution Enablement  Administrator (.*)",
        "FACTS Project Manager 541-475-2234 ex 175(.*)",
        "This e-mail and any attachments are(.*)",
        "Good Evening,",
        "Dear Blueworks Team",
        "\!\!\!(.*)",
        ", I am the Global Client Director for .",
        "Ramesh B.M Subject IBM(.*)",
        "CALLOWN(.*)",
        "Manager \| \| 305 715 6782(.*)",
        "NPE Valuations Manager(.*)",
        "\| Control Enhancement Manager(.*)",
        "\| Tel \+44 \(0\)20 7116 5558 \|(.*)",
        "Dear IBM Team,(.*)",
        "The attachment\(s\) appendix1_ibm_bwl_cloud_services_descri"
    ]
}
